version: "2"

linters:
  enable:
    - bodyclose
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - unconvert
    - unparam
    - nilerr
  disable:
    - errcheck
